# Generated by Django 5.0.6 on 2024-05-20 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vigilantenotifica",
            old_name="patente",
            new_name="vehiculo",
        ),
    ]
