# Generated by Django 5.0.6 on 2024-05-28 20:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0003_rename_patente_vigilantenotifica_vehiculo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedBack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comentario", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("leido", models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameModel(
            old_name="Estacionamientos",
            new_name="Estacionamiento",
        ),
        migrations.RenameModel(
            old_name="Sedes",
            new_name="Sede",
        ),
        migrations.RenameModel(
            old_name="Vehiculos",
            new_name="Vehiculo",
        ),
        migrations.AddField(
            model_name="vigilantenotifica",
            name="leido",
            field=models.BooleanField(default=False),
        ),
    ]
