repos:
  - repo: local
    hooks:
      - id: generate-requirements
        name: generate-requirements
        entry: python -m hooks.generate-requirements
        language: system
        types: [python]
        always_run: true

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
