services:
  app:
    restart: always
    build:
      context: ./backend
      dockerfile: ./env.dockerfile
    develop:
      watch:
        - action: sync
          path: ./backend/
          target: ./
    volumes:
      - ./django_volume/:/staticfiles/
    expose:
      - "8000"
    env_file:
      - .env
    environment:
      - DOCKER_CONTAINER=1
      - DEV=1
    container_name: uparking_backend
    depends_on:
      - database
    command: >
      sh -c "python manage.py makemigrations administration authentication &&
          python manage.py makemigrations --merge &&
          python manage.py migrate &&
          python manage.py collectstatic --no-input &&
          gunicorn uparking.wsgi:app --bind 0.0.0.0:8000 --reload --log-level debug --capture-output"

  database:
    image: "postgis/postgis"
    container_name: uparking_database
    ports:
      - 15432:5432
    env_file:
      - .env
    volumes:
      - ./volumes/db-data/:/var/lib/postgresql/data/
    logging:
      driver: none

  pgadmin:
    image: dpage/pgadmin4
    container_name: uparking_pgadmin
    ports:
      - 15433:80
    env_file:
      - .env
    depends_on:
      - database
    volumes:
      - ./volumes/pgadmin-data/:/var/lib/pgadmin/
    logging:
      driver: none

  nginx:
    build:
      context: ./frontend
      dockerfile: ./env.dockerfile
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf
      - ./django_volume/:/staticfiles/
    depends_on:
      - app

volumes:
  django_volume:
