version: '3.9'

services:
  app:
    build: . 
    volumes: 
      - .:/backend
    ports:
      - 8000:8000
    env_file:
      - .env
    image: app:django
    depends_on:
      - database
    container_name: backend_container
    command: python manage.py runserver 0.0.0.0:8000

    database:
    image: 'postgres:latest'
    ports:
      - 15432:5432
    env_file:
      - .env
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
  
    pgadmin:
      image: dpage/pgadmin4
      ports:
        - 15433:80
      env_file:
        - .env
      depends_on:
        - database
      networks:
        - postgres-network
      volumes:
        - ./pgadmin-data/:/var/lib/pgadmin/
