# Generated by Django 5.0.6 on 2024-06-18 18:16

from django.conf import settings
from django.db import migrations


def update_site_name(apps, schema_editor):
    site_model = apps.get_model("sites", "Site")
    domain = "csep.dev"

    site_model.objects.update_or_create(
        pk=settings.SITE_ID, defaults={"domain": domain, "name": domain}
    )


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("administration", "0002_initial"),
        ("sites", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(update_site_name),
    ]
