# Generated by Django 5.0.6 on 2024-06-09 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="s_apellido",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="s_nombre",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
