# Generated by Django 5.0.6 on 2024-06-10 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_customuser_s_apellido_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="telefono",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
