# Generated by Django 5.0.6 on 2024-05-17 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="rol2",
            field=models.CharField(default="user", max_length=11),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="rol",
            field=models.CharField(default="user", max_length=11),
        ),
    ]
