# Generated by Django 5.0.6 on 2024-05-17 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_customuser_rol2_alter_customuser_rol"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="rol2",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="rol",
            field=models.CharField(default="user", max_length=10),
        ),
    ]
